language: cpp
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx  
compiler:
  - gcc
  - clang
  - CXX=g++-mingw-w64-x86-64; g++
before_install:
  - openssl aes-256-cbc -K $encrypted_24fdd259e571_key -iv $encrypted_24fdd259e571_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
install:
 - if [ "$CXX" = "g++" ]; then sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list; fi
 - if [ "$CXX" = "g++-mingw-w64-x86-64" ]; then sudo sed -i 's/precise/trusty/g' /etc/apt/sources.list; fi
 - sudo apt-get update -qq
 - sudo apt-get install libsdl1.2-dev libopenal-dev
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qqy gcc g++; fi
 - if [ "$CXX" = "g++-mingw-w64-x86-64" ]; then sudo apt-get install -qqy g++-mingw-w64-x86-64; fi
script: mkdir build && cd build &&  if [ "$CXX" = "g++-mingw-w64-x86-64" ]; then cmake -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../scripts/mingw32.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DSDL2=OFF -DBUNDLED_FREETYPE=ON -DBUNDLED_OPENAL=ON ../ ;else cmake -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DSDL2=OFF ../;fi && make
after_success:
 - cd ..
 - chmod 600 .travis/id_rsa
 - mkdir OpenTechEngine
 - cp -a base OpenTechEngine/
 - if [ "$CXX" = "g++-mingw-w64-x86-64" ]; then cp build/OpenTechEngine.exe OpenTechEngine/; else cp build/OpenTechEngine OpenTechEngine/; fi
 - tar cjf OpenTechEngine.tar.bz2 OpenTechEngine
 - scp -B -i .travis/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no OpenTechEngine.tar.bz2 kordex@frs.sourceforge.net:/home/frs/project/testrepositoryproject/TestRel/$(date +%s).$CXX.OpenTechEngine.tar.bz2
